In [2]:
import pandas as pd
import numpy as np

In [3]:
df_users = pd.read_csv(r"C:\Users\ASUS\Documents\College folders\Placements\Projects\Product Analyst\Raw data\raw__users_202607171732.csv")

In [4]:
df_users

,user_id,account_id,full_name,email,job_role,user_status,created_at,last_seen_at,timezone,locale,is_admin
0,user_1,account_82,Ingrid Hansen,ingrid.hansen@salesops.eu,sales_rep,active,2026-06-09 05:17:49.000,2027-05-21 23:53:49.000,Europe/Oslo,fr-FR,False
1,user_2,account_26,Ethan Nilsson,ethan.nilsson@acme-eu.com,sales_rep,active,2029-09-12 09:51:54.000,2029-09-15 15:17:54.000,Europe/London,de-DE,False
2,user_3,account_13,Leo Thomas,leo.thomas@salesops.eu,sales_manager,active,2029-02-07 14:22:22.000,2029-10-01 08:40:22.000,Europe/Oslo,de-DE,False
3,user_4,account_25,Lucas Johansson,lucas.johansson@acme-eu.com,revops,invited,2029-08-21 16:33:21.000,NaN,Europe/Stockholm,nl-NL,False
4,user_5,account_27,Lea Bakker,lea.bakker@nordicflow-customer.com,sales_manager,active,2029-02-06 15:49:02.000,2029-06-11 21:23:02.000,Europe/Berlin,de-DE,False
...,...,...,...,...,...,...,...,...,...,...,...
395,user_396,account_79,Emma Wilson,emma.wilson@acme-eu.com,sales_rep,active,2029-12-03 17:04:54.000,2029-12-24 00:00:00.000,Europe/Amsterdam,nb-NO,False
396,user_397,account_43,Lina Brown,lina.brown@example.eu,customer_success,active,2028-03-20 11:01:04.000,2028-08-21 06:18:04.000,Europe/London,en-GB,False
397,user_398,account_114,Leo Nielsen,leo.nielsen@acme-eu.com,sales_rep,active,2027-08-06 21:59:24.000,2028-06-22 16:13:24.000,Europe/Amsterdam,sv-SE,False
398,user_399,account_91,Adam Bakker,adam.bakker@nordicflow-customer.com,sales_rep,active,2029-09-24 10:44:48.000,2029-12-24 00:00:00.000,Europe/Amsterdam,da-DK,False
399,user_400,account_117,Maja Schmidt,maja.schmidt@midmarket.io,sales_rep,active,2028-02-16 19:22:33.000,2028-05-05 01:51:33.000,Europe/Copenhagen,de-DE,False

In [5]:
df_users['user_status'] = df_users['user_status'].str.lower()

In [6]:
date_columns = ['last_seen_at', 'created_at']  # to convert date columns from object to date
df_users[date_columns] = df_users[date_columns].apply(pd.to_datetime)

In [7]:
df_users['days_last_seen'] = (df_users['last_seen_at'] - pd.Timestamp.now()).dt.days

In [8]:
df_users['created_at'] = df_users['created_at'].dt.date
df_users['last_seen_at'] = df_users['last_seen_at'].dt.date

In [9]:
df_users

,user_id,account_id,full_name,email,job_role,user_status,created_at,last_seen_at,timezone,locale,is_admin,days_last_seen
0,user_1,account_82,Ingrid Hansen,ingrid.hansen@salesops.eu,sales_rep,active,2026-06-09,2027-05-21,Europe/Oslo,fr-FR,False,307.0
1,user_2,account_26,Ethan Nilsson,ethan.nilsson@acme-eu.com,sales_rep,active,2029-09-12,2029-09-15,Europe/London,de-DE,False,1154.0
2,user_3,account_13,Leo Thomas,leo.thomas@salesops.eu,sales_manager,active,2029-02-07,2029-10-01,Europe/Oslo,de-DE,False,1170.0
3,user_4,account_25,Lucas Johansson,lucas.johansson@acme-eu.com,revops,invited,2029-08-21,NaT,Europe/Stockholm,nl-NL,False,NaN
4,user_5,account_27,Lea Bakker,lea.bakker@nordicflow-customer.com,sales_manager,active,2029-02-06,2029-06-11,Europe/Berlin,de-DE,False,1059.0
...,...,...,...,...,...,...,...,...,...,...,...,...
395,user_396,account_79,Emma Wilson,emma.wilson@acme-eu.com,sales_rep,active,2029-12-03,2029-12-24,Europe/Amsterdam,nb-NO,False,1254.0
396,user_397,account_43,Lina Brown,lina.brown@example.eu,customer_success,active,2028-03-20,2028-08-21,Europe/London,en-GB,False,764.0
397,user_398,account_114,Leo Nielsen,leo.nielsen@acme-eu.com,sales_rep,active,2027-08-06,2028-06-22,Europe/Amsterdam,sv-SE,False,704.0
398,user_399,account_91,Adam Bakker,adam.bakker@nordicflow-customer.com,sales_rep,active,2029-09-24,2029-12-24,Europe/Amsterdam,da-DK,False,1254.0
399,user_400,account_117,Maja Schmidt,maja.schmidt@midmarket.io,sales_rep,active,2028-02-16,2028-05-05,Europe/Copenhagen,de-DE,False,656.0

In [10]:
import mysql.connector as connection
from mysql.connector import Error

mydb = connection.connect(host='localhost',user='root',password='BobySQL2026',database='product_analysis', use_pure=True)

In [12]:
from sqlalchemy import create_engine
db_credentials = "mysql+pymysql://root:BobySQL2026@localhost:3306/product_analysis"
engine = create_engine(db_credentials)

dim_users = df_users
dim_users.to_sql(
    name = "gold_fact_users",
    con = engine,
    if_exists = 'replace',
    index = False
)

400