In [1]:
import pandas as pd
import numpy as np

In [2]:
df_accounts = pd.read_csv(r"C:\Users\ASUS\Documents\College folders\Placements\Projects\Product Analyst\Raw data\raw__accounts_202607171731.csv")
df_geography = pd.read_excel(r"C:\Users\ASUS\Documents\College folders\Placements\Projects\Product Analyst\Raw data\Module_2_raw__geography--.xlsx")

In [3]:
df_accounts.shape

(120, 12)

In [4]:
df_accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   account_id           120 non-null    object
 1   account_name         120 non-null    object
 2   country_code         120 non-null    object
 3   city                 120 non-null    object
 4   industry             116 non-null    object
 5   employee_band        120 non-null    object
 6   segment              120 non-null    object
 7   created_at           120 non-null    object
 8   trial_start_date     93 non-null     object
 9   trial_end_date       93 non-null     object
 10  account_status       120 non-null    object
 11  acquisition_channel  120 non-null    object
dtypes: object(12)
memory usage: 11.4+ KB

In [5]:
df_accounts.describe()

,account_id,account_name,country_code,city,industry,employee_band,segment,created_at,trial_start_date,trial_end_date,account_status,acquisition_channel
count,120,120,120,120,116,120,120,120,93,93,120,120
unique,120,115,10,35,7,4,2,120,89,89,4,5
top,account_1,Bright Craft Networks,SE,Uppsala,Technology Services,20-49,SMB,2026-02-08 20:28:06.000,2029-08-31,2029-09-14,active,sales-led
freq,1,2,25,8,21,52,83,1,2,2,100,30

In [6]:
df_accounts.isnull().sum()

account_id              0
account_name            0
country_code            0
city                    0
industry                4
employee_band           0
segment                 0
created_at              0
trial_start_date       27
trial_end_date         27
account_status          0
acquisition_channel     0
dtype: int64

In [8]:
df_accounts["account_name"].str.strip()
df_accounts["country_code"].str.strip()

0      UK
1      UK
2      NL
3      FR
4      SE
       ..
115    NL
116    UK
117    UK
118    SE
119    DK
Name: country_code, Length: 120, dtype: object

In [9]:
df_accounts = df_accounts.dropna(subset = ['industry'])

In [10]:
date_columns = ['trial_start_date', 'trial_end_date']  # to convert date columns from object to date
df_accounts[date_columns] = df_accounts[date_columns].apply(pd.to_datetime)

In [11]:
cleanup_mapping = {
    'product-led' : 'product_led',
    'sales-led' : 'sales_led'
}

df_accounts['acquisition_channel'] = df_accounts['acquisition_channel'].replace(cleanup_mapping)

In [12]:
cleanup_country = {
    ' DE ' : 'DE',
    ' DK ' : 'DK',
    'no' : 'NO'
}

df_accounts['country_code'] = df_accounts['country_code'].replace(cleanup_country)

In [13]:
df_accounts['trial_days'] = (df_accounts['trial_end_date'] - df_accounts['trial_start_date']).dt.days

In [14]:
df_combined = pd.merge(df_accounts, df_geography, how = 'left', on = 'country_code', suffixes = ('_Left','_Right'))

In [15]:
df_combined

,account_id,account_name,country_code,city,industry,employee_band,segment,created_at,trial_start_date,trial_end_date,account_status,acquisition_channel,trial_days,country_name,region,market,currency,sales_region
0,account_1,Euro Pulse Consulting AS,UK,London,SaaS,20-49,SMB,2026-02-08 20:28:06.000,2026-02-08,2026-02-22,active,paid_search,14.0,United Kingdom,UKI,UKI,GBP,UK & Ireland
1,account_2,Vertex Peak Services SAS,UK,Bristol,SaaS,100-199,Mid-Market,2027-10-14 16:49:57.000,2027-10-14,2027-10-28,active,sales_led,14.0,United Kingdom,UKI,UKI,GBP,UK & Ireland
2,account_3,Bright Link Networks,NL,Utrecht,Manufacturing,20-49,SMB,2029-06-07 19:55:23.000,2029-06-07,2029-06-21,active,product_led,14.0,NaN,NaN,NaN,NaN,NaN
3,account_4,Blue Peak Logistics,FR,Marseille,Manufacturing,50-99,SMB,2026-05-04 22:51:37.000,NaT,NaT,cancelled,partner,NaN,France,Southern Europe,Southern Europe,EUR,South Europe
4,account_4,Blue Peak Logistics,FR,Marseille,Manufacturing,50-99,SMB,2026-05-04 22:51:37.000,NaT,NaT,cancelled,partner,NaN,France,Southern Europe,Southern Europe,EUR,South Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,account_116,Atlas Pulse Trading Ltd,NL,Utrecht,Logistics,200-300,Mid-Market,2029-08-07 02:41:40.000,2029-08-07,2029-08-21,active,sales_led,14.0,NaN,NaN,NaN,NaN,NaN
125,account_117,Nordic Pulse Services,UK,Bristol,SaaS,100-199,Mid-Market,2027-06-09 11:22:13.000,NaT,NaT,active,product_led,NaN,United Kingdom,UKI,UKI,GBP,UK & Ireland
126,account_118,Atlas Wave Partners,UK,Bristol,Technology Services,20-49,SMB,2027-03-26 23:44:31.000,2027-03-26,2027-04-09,active,content,14.0,United Kingdom,UKI,UKI,GBP,UK & Ireland
127,account_119,Apex Track Trading AB,SE,Malmö,Manufacturing,100-199,Mid-Market,2029-08-31 06:29:29.000,2029-08-31,2029-09-14,active,sales_led,14.0,Sweden,Nordics,Nordic,SEK,North Europe
128,account_120,Iron Peak Systems,DK,Aalborg,Professional Services,100-199,Mid-Market,2029-09-04 10:21:48.000,2029-09-04,2029-09-18,active,partner,14.0,Denmark,Nordics,Nordic,DKK,North Europe

In [ ]:
df_combined.drop('no_of_days', axis = 1)

In [16]:
import mysql.connector as connection
from mysql.connector import Error

mydb = connection.connect(host='localhost',user='root',password='BobySQL2026',database='product_analysis', use_pure=True)

In [19]:
from sqlalchemy import create_engine
db_credentials = "mysql+pymysql://root:BobySQL2026@localhost:3306/product_analysis"
engine = create_engine(db_credentials)

dim_accounts = df_combined
dim_accounts.to_sql(
    name = "gold_fact_accounts",
    con = engine,
    if_exists = 'replace',
    index = False
)

129